-- V4__update_amenities.sql
-- Houseテーブルのamenitiesカラムを一括更新（id=1〜57）
-- 開発用データ。ランダム内容。

UPDATE houses
SET amenities = CASE id
  WHEN 1 THEN 'Wi-Fi・冷暖房・キッチン'
  WHEN 2 THEN '温泉・駐車場・テレビ'
  WHEN 3 THEN 'バルコニー・洗濯機・乾燥機'
  WHEN 4 THEN 'Wi-Fi・電気ケトル・ミニ冷蔵庫'
  WHEN 5 THEN '浴室乾燥機・加湿器・アイロン'
  WHEN 6 THEN 'ペット可・庭付き・バーベキューグリル'
  WHEN 7 THEN 'オーシャンビュー・キッチン・電子レンジ'
  WHEN 8 THEN 'プロジェクター・Bluetoothスピーカー・ソファ'
  WHEN 9 THEN 'サウナ・ジャグジー・テラス'
  WHEN 10 THEN 'エアコン・テレビ・無料Wi-Fi'
  WHEN 11 THEN 'コーヒーメーカー・電子レンジ・洗濯機'
  WHEN 12 THEN 'バーベキューセット・冷蔵庫・庭園'
  WHEN 13 THEN '専用ドッグラン・ペット可・屋外照明'
  WHEN 14 THEN 'IHコンロ・食器洗浄機・オーブン'
  WHEN 15 THEN '暖炉・マッサージチェア・加湿器'
  WHEN 16 THEN 'ジャグジー・バスタブ・大画面テレビ'
  WHEN 17 THEN '電気毛布・湯沸かしポット・Wi-Fi'
  WHEN 18 THEN '屋外テラス・日よけパラソル・冷蔵庫'
  WHEN 19 THEN '簡易キッチン・電気ケトル・洗濯機'
  WHEN 20 THEN '暖房・ソファベッド・ドライヤー'
  WHEN 21 THEN '冷暖房・IHヒーター・冷蔵庫'
  WHEN 22 THEN 'サウナ・露天風呂・無料駐車場'
  WHEN 23 THEN 'オーブン・調理器具・食器類'
  WHEN 24 THEN 'Wi-Fi・庭付き・シーリングファン'
  WHEN 25 THEN '屋外シャワー・テラス・バーベキュー設備'
  WHEN 26 THEN 'キッチン・バスタブ・電気毛布'
  WHEN 27 THEN 'Netflix対応TV・Bluetoothスピーカー・ソファ'
  WHEN 28 THEN '電子レンジ・コーヒーメーカー・炊飯器'
  WHEN 29 THEN 'Wi-Fi・冷暖房・ベランダ'
  WHEN 30 THEN '洗濯機・乾燥機・冷蔵庫'
  WHEN 31 THEN 'ミニキッチン・トースター・IHコンロ'
  WHEN 32 THEN '無料駐車場・温泉・テレビ'
  WHEN 33 THEN 'バルコニー・ソファ・Wi-Fi'
  WHEN 34 THEN '屋外照明・バーベキューセット・ペット可'
  WHEN 35 THEN '加湿器・空気清浄機・オーブン'
  WHEN 36 THEN 'キッチン用品・コーヒー豆・電気ポット'
  WHEN 37 THEN 'ジャグジー・バスタブ・照明付きテラス'
  WHEN 38 THEN 'Wi-Fi・冷暖房・洗濯乾燥機'
  WHEN 39 THEN '浴室乾燥機・IHコンロ・電子レンジ'
  WHEN 40 THEN '庭付き・ハンモック・冷蔵庫'
  WHEN 41 THEN 'Wi-Fi・サウナ・温泉'
  WHEN 42 THEN 'プロジェクター・Bluetoothスピーカー・ソファ'
  WHEN 43 THEN '洗濯機・乾燥機・掃除機'
  WHEN 44 THEN '無料駐車場・冷暖房・冷蔵庫'
  WHEN 45 THEN 'Wi-Fi・屋外テラス・バーベキューグリル'
  WHEN 46 THEN 'テレビ・電気ケトル・電子レンジ'
  WHEN 47 THEN 'オーブン・食器洗浄機・IHコンロ'
  WHEN 48 THEN '庭付き・ハンモック・Wi-Fi'
  WHEN 49 THEN '洗濯機・乾燥機・冷蔵庫'
  WHEN 50 THEN 'サウナ・露天風呂・無料Wi-Fi'
  WHEN 51 THEN '暖房・ソファ・Bluetoothスピーカー'
  WHEN 52 THEN 'ミニバー・冷蔵庫・コーヒーメーカー'
  WHEN 53 THEN 'Wi-Fi・洗濯機・ドライヤー'
  WHEN 54 THEN 'オーシャンビュー・テラス・ハンモック'
  WHEN 55 THEN 'ペット可・ドッグラン・屋外照明'
  WHEN 56 THEN 'バーベキュー設備・庭付き・冷暖房'
  WHEN 57 THEN 'ジャグジー・マッサージチェア・シーリングファン'
  ELSE amenities
END;
